### ISSUE TITLE
Decide on XML element naming convention

### ISSUE THREAD

**Issue by mikesteez** [erasmus-without-paper/issues#15]
We are working with the IIAS API currently, and we have one suggestion. 

Could we change 

`<xs:element name="response">`

To something like 

`<xs:element name="IIASIndexResponse">`

and unique names for all root elements in the XSD files? We get collisions when we generate Java code from the schemas, as everything is named “response”. It is also quite confusing in the code, when all you have is different Reponse objects, only separated by the package name.

**Comment by wrygiel** [comment]
I don't mind renaming these. @erasmus-without-paper/wp3, @erasmus-without-paper/wp4, what do you think?

Also, I think we should agree on a single "XML element naming convention". I have used `<words-separated-by-dashes>` so far, because this is what W3C standards tend to use, I think. I don't mind using different conventions, as long as we stick with them in all the other draft APIs.

**Comment by kaiqu** [comment]
Both unique response names and dash-as-separator are fine by me.

**Comment by georgschermann** [comment]
We are also fine with both variants. Personally i tend to pascal casing.

**Comment by wrygiel** [comment]
> Personally i tend to pascal casing.

Since we intend to reuse EMREX ELMO schemas, and these schemas use `pascalCasing`, then I can see a reason to use it in EWP too. Unfortunatelly, we have started to use `spacing-with-dashes` in some of the released APIs already, so we will end up with some mixed conventions either way... Hmm...

**Comment by wrygiel** [comment]
On the other hand, having mixed conventions is pretty natural in XML world. For example, EMREX ELMO uses `pascalCasing`, but it also imports XML signing schema which uses `UpperCase` ([example here](https://github.com/emrex-eu/elmo-schemas/blob/69fe9e4b8021f5f118835c9f213f6d39af412c4f/example.xml#L168)). So, perhaps we're overthinking this.

**Comment by georgschermann** [comment]
I also think it's nothing worth putting too much effort in it.
