### ISSUE TITLE
Comments/questions on XSD + where to upload data model?

### ISSUE THREAD

**Issue by kaiqu** [erasmus-without-paper/issues#16]
Hi,

I have a new version of the data model + some comments on the response schemas ready for upload, but I am not sure where to put the former: Should the data model be in a separate repository? If not, where? ewp-specs-architecture? general-issues?

Due to my lack of in-depth knowledge of XSD (being a database modeler and developer), I will upload a comments/questions document in the appropriate repos, instead of modifying the response schemas directly.

**Comment by wrygiel** [comment]
> Should the data model be in a separate repository?

Yes, I think so. I have created an empty repository for you here: https://github.com/erasmus-without-paper/ewp-wp3-data-model

> Due to my lack of in-depth knowledge of XSD (being a database modeler and developer), I will upload a comments/questions document in the appropriate repos, instead of modifying the response schemas directly.

I think that the easiest way to start discussion on a certain topic is to submit a new issue, and possibly quote a section of the XSD you are commenting on (or paste a permalink to such section).

If you're more experienced with GitHub, then you can also play with GitHub's forks and pull requests (this way you can propose modifications without modifying the "master copy").

**Comment by wrygiel** [comment]
BTW, I'm not sure if you are aware, but most of the XSDs currently committed in the draft specifications are just placeholders. (Not much to comment on.)

We are still waiting for you (WP3) to fill them out. So, you might want to discuss these issues internally in Oslo first. We are hoping for WP3 to present the new XSDs and talk trough them in detail during the meeting in Warsaw.

**Comment by kaiqu** [comment]
We are having an internal discussion here asap, to clear up any misunderstandings. As for presenting XSDs in Warsaw, one problem is that the "XML guy" (Richard) is on paternity leave until the beginning of October. The rest of us aren't very proficient in XML, but we will see what we can do...

BTW, how do you quote from earlier comments?

**Comment by wrygiel** [comment]
> The rest of us aren't very proficient in XML, but we will see what we can do...

If you don't feel comfortable with XSDs, then try to prepare example XML responses (for each of the APIs).  Writing example XMLs is much easier, I think. We can make fully-documented XSDs out of them later (after we discuss them in Warsaw). Since these are drafts, you can put them in Google Docs too, for easier editing, and we will update official specification proposals afterwards.

> BTW, how do you quote from earlier comments?

[This](https://github.com/blog/1399-quick-quotes) may help :)

**Comment by kaiqu** [comment]
> If you don't feel comfortable with XSDs, then try to prepare example XML responses (for each of the APIs).  Writing example XMLs is much easier, I think. We can make fully-documented XSDs out of them later (after we discuss them in Warsaw). Since these are drafts, you can put them in Google Docs too, for easier editing, and we will update official specification proposals afterwards.

Sounds good.

> > BTW, how do you quote from earlier comments?
> 
> This may help :)

Thanks :-)

**Comment by kaiqu** [comment]
I have committed example responses which hopefully will work as starting points for discussion.

I have concentrated on including pertinent information (data types could probably be more modularized,, maybe some of the elements should be attributes or vice versa...)

**Comment by wrygiel** [comment]
I have read all your XML examples and added some comments (I have also replaced all the tabs with spaces, to keep indenting consistent across files and projects.)
