### ISSUE TITLE
Problems finding the format examples?

### ISSUE THREAD

**Issue by kaiqu** [erasmus-without-paper/issues#17]
Geir said people have problems finding the examples I uploaded last week.

They were committed to the same directories as the schemas (master branch, I think), and called typically response-example.xml. I see them in GitHub myself?

(Btw, I am home with a cold today, so I will only be reading email sporadically)

**Comment by wrygiel** [comment]
It's okay, your examples are properly committed, I will try to find some time to review them this week.

GitHub doesn't send notifications to anyone unless they have explicitly subscribed to receive such notifications. And, in case of individual commits, you need to subscribe to RSS feed if you want to receive git push notifications for all of your watched repositories.

So, whenever you want _everyone_ to take a look at something you have recently committed, it's best to post a link to technical@erasmuswithoutpaper.eu.
