### ISSUE TITLE
Rules on keeping old entities?

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/issues#20]
Should we document some rules, or at least recommendations, on the subject of keeping obsolete EWP entities "visible"?

First, a quote from [this issue](https://github.com/erasmus-without-paper/ewp-specs-api-courses/issues/10):

>>  I don't see any use case within EWP to request the complete course catalog over the years
>
> (...) I think that your EWP partners should be fine if you decide to "hide" [LOSes/LOIs] older than, say, a year or two. The only thing we require from implementers is to be consistent - for example, if you refer to a local LOS/LOI in any of your Outgoing Mobilities API, then this LOS/LOI MUST be accessible via your Courses API. Note, that this brings us to a related issue - for how long should old mobilities be accessible?

I will expand on this answer a bit:

When I was documenting the APIs I noticed that keeping (and exposing) a full history seems to be the easiest way for developers to keep that said consistency. I myself would probably tend to do it this way, for simplicity. But I know that this topic is disputable, because I often tend to argue about such issues with @janinamincer-daszkiewicz. So I open this issue here.

Problems:

1. Is it *okay* for a server to keep data on very old entities visible? This includes very old LOSes and LOIs, very old IIAs and mobilities.

Our current answer: It's always acceptable, but it's not required. Server implementers MAY decide to hide old entities - but if they do, they MUST hide them consistently (as described by the example quoted above).

2. Should we require servers to keep data on old entities visible?

I do believe that it's NOT okay to hide such entries "too early". And I think we should decide on what this "too early" exactly means. For example:

* An outgoing mobility shouldn't just disappear after the student returns from this mobility - the receiving HEI should still be allowed to access it for some time afterwards,
* A LOS which has stopped being conducted should still be visible for some time, because external HEIs MAY keep references to this LOS in their databases.

Can we, for example, make it "RECOMMENDED" to keep such obsolete entities online "at least 2 years after they got obsolete"?

@erasmus-without-paper/all-members

**Comment by georgschermann** [comment]
+1 for recommendation to keep them and to hide them consistently if needed.

But we as a service provider are in no position to tell our customers how long they have to keep their data.
When an university decides to delete all personal data at the time where it is no longer required, then its gone.
We would mirror all data which could be required at a later point into our own system, and would never rely on third party systems to provide information which is crucial for us.

**Comment by wrygiel** [comment]
Added "Referential integrity" and "Keeping old data" chapters [here](https://github.com/erasmus-without-paper/ewp-specs-architecture/tree/1765dc5e9085a98396064c47d8389d8563ac02ab#referential-integrity).
