### ISSUE TITLE
Retrieving entities by code (not only by id)

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/issues#21]
One of the recent changes to many specifications was [adding the distinction between IDs and codes](https://github.com/erasmus-without-paper/ewp-specs-api-mobilities/issues/9). One of the consequences of this is that we can no longer access (or search) entities by their codes (natural keys) - currently we can do this only by their IDs (surrogate keys).

Perhaps we should modify the existing `get` endpoints, so that they may take not only a list of IDs, but also a list of codes? The server would be required to scan both lists, and return matching entries in the response.

I think it might be useful. Please comment. @erasmus-without-paper/all-members

**Comment by wrygiel** [comment]
Example use case:

When a student manually enters the course code on his LA (on the sending HEI system), the page can attempt to request more information on this course (by its code) from the receiving HEI system. Of course, this will work only if the student enters the code without any mistakes (the code is case sensitive), but I would still consider this useful.

**Comment by kaiqu** [comment]
> Perhaps we should modify the existing get endpoints, so that they may take not only a list of IDs, but also a list of codes? The server would be required to scan both lists, and return matching entries in the response.

Fine by me.

**Comment by wrygiel** [comment]
Developers, [here](https://github.com/erasmus-without-paper/ewp-specs-api-ounits/commit/c516ae2122d8782702d7a4a9dcb951b0c93415d7) you can see an example of how this change will look like (in case Organizational Units API). We will prepare similar changes for Courses API and IIAs API.
