### ISSUE TITLE
Set a limit on length and charset of all primary EWP IDs?

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/issues#23]
During the adoption of EWP, partners will be required to store identifiers generated by other partners. This means that partners will need to add new columns to their databases. What should be the type and length of such columns?

The longest identifier actually [suggested](https://github.com/erasmus-without-paper/ewp-specs-api-courses/blob/v0.4.0/response-example.xml#L72) by the current specifications contains 40 characters. Also, currently we do not set any restrictions as to the character set of these identifiers.

I believe we should set some limits here. These limits could (probably?) be validated by the schema. My suggestion for this limit would be 50 case-sensitive ASCII characters (but not *all* ASCII bytes... this requires some further thought I think).

@erasmus-without-paper/all-members

**Comment by kaiqu** [comment]
They should be able to store UUIDs at a minimum (hex representation without hyphens = 32), and I doubt anyone needs more than 50. As for which ASCII characters, I would think the printable range (32-127) should be good(?)

**Comment by huntering** [comment]
Ok for the limit, OK for the ASCII characters. 50 is OK for us but maybe we should take a bit more to be on the safe side? e.g. 64

**Comment by wrygiel** [comment]
> I would think the printable range (32-127) should be good(?)

Hard to tell. There are still some possibly troublesome characters in this range (such as `>`, `&`, space or a [delete character](https://en.wikipedia.org/wiki/Delete_character)). Perhaps we could limit this even further? For example, could we use `[a-zA-Z0-9/_-]{1,64}`?

**Comment by huntering** [comment]
Maybe add ":@+." ? Others?

**Comment by kaiqu** [comment]
>> There are still some possibly troublesome characters in this range (such as `>`, `&`, Space

I can see that `<>&` could make trouble in XML, but space as well?

>> or a delete character).

This one was a typo - I meant 126 (127 isn't printable).

>> Perhaps we could limit this even further? For example, could be use [a-zA-Z0-9/_-]{1,64}?
>
> Maybe add ":@+." ? Others?

I leave this to you guys...

**Comment by wrygiel** [comment]
> I can see that `<>&` could make trouble in XML, but space as well?

Not really trouble in XML, but rather a precaution against IDs such as `"123 "` (typos, programming errors). I feel that spaces tend to make *more* trouble than all the other characters I have mentioned.

Maybe ASCII range 33-126 would be a good choice?

**Comment by wrygiel** [comment]
BTW - note that I propose that this limit should be set only for surrogate keys (like `ounit_id`), not the natural keys (like `ounit_code`).

Natural keys are treated exactly as all the other `xs:string` attributes, so I don't think we need to set any length limits on them. (They will also often contain non-ASCII characters.)

**Comment by kaiqu** [comment]
I'm fine with it.

**Comment by wrygiel** [comment]
The newly introduced limits are explained [here](https://github.com/erasmus-without-paper/ewp-specs-architecture/tree/5901a1b52c69414509624b2df07e13e9cab0683c#identifiers-surrogate-vs-natural-keys).
