### ISSUE TITLE
Create a draft version of EMREX Gateway API

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/issues#30]
This is the first step required before joining EMREX and EWP registries, as explained [here](https://github.com/erasmus-without-paper/general-issues/issues/29).

**Comment by wrygiel** [comment]
I pushed it [here](https://github.com/erasmus-without-paper/ewp-specs-api-emrex-gateway/tree/v0.1.0).

I wrote a draft specification only - I didn't have time to:

1. Update the developers page.
2. Pull the new XSDs to the Registry Service implementation to validate them.

**Comment by janinamincer-daszkiewicz** [comment]
Anyway, thanks a lot. We will continue.
