### ISSUE TITLE
Dashboard-EWP: student in Dashboard and coordinator in SIS scenario

### ISSUE THREAD

**Issue by MartaJuzepczuk** [erasmus-without-paper/issues#32]
Fragment of summary from the email discussion (Paul Leys):

> In the meeting in Brussels we agreed on two use cases:
> 
> 1) OLA is used by both students (2) and coordinators (3) (I tried to illustrate this, see [1_flow_LA_OLA](https://user-images.githubusercontent.com/28525031/58400357-125d6280-805b-11e9-8c2d-de331fe71755.JPG))
> 
> 2) SIS is used for both students (2) and coordinators (3), update is send to OLA (see [2_flow_LA_SIS](https://user-images.githubusercontent.com/28525031/58400356-125d6280-805b-11e9-9b87-dad1aff927ad.jpg)
).
> 
> Now there is an additional use case for institutions that want to use OLA as 
> student interface (2) and their own SIS (instead of dashboard) as coordinators 
> interface (3) (see [3_flow_LA_OLA_SIS](https://user-images.githubusercontent.com/28525031/58400355-11c4cc00-805b-11e9-89d2-4a90f848a6af.JPG)). Problem with this flow is about data exchange 
> between OLA and SIS (line marked in red). The current architecture of EWP cannot 
> handle this data flow, right?

**Comment by BavoNootaert** [comment]
In diagram 1 there appears to be a student from Alcala going to Porto. What is the role of Ghent University in this scenario? (And the same question for diagram 3.)

**Comment by EvelienRenders** [comment]
@BavoNootaert and @MartaJuzepczuk , I guess University of Porto is just a mistake leftover from another diagram. So that should be changed into Ghent University in all three diagrams.

> The current architecture of EWP cannot handle this data flow, right?

**The question about this data flow** is interesting though. 

- [ ] 1. Are you saying that only ErasmusDashboard is going to communicate via EWP, and not the OLA directly?
- [ ] 2. How does the data arrive at the E+ app? Is that not also done via ErasmusDashboard?
- [ ] 3. Would this problem be solved just by putting the ErasmusDashboard in the red arrow? Then the information would go from OLA > ED > Vienna

Please also let me know if I'm talking complete bullshit and should not participate in the discussion ;)! Just trying to get a grip on the processes :)

**Comment by MartaJuzepczuk** [comment]
> @BavoNootaert and @MartaJuzepczuk , I guess University of Porto is just a mistake leftover from another diagram. So that should be changed into Ghent University in all three diagrams.

In the second one it is ok. There are two universities having their own SIS (Porto and Ghent) talking via EWP. In the first and the third one there is probably some mistake. Maybe @pleys can confirm?

> **The question about this data flow** is interesting though.
> 
> * [ ]  1. Are you saying that only ErasmusDashboard is going to communicate via EWP, and not the OLA directly?
> * [ ]  2. How does the data arrive at the E+ app? Is that not also done via ErasmusDashboard?

I'm not a good person to answer this two questions. For me, as the EWP developer, the Dashboard, OLA and E+ app are almost the same. What we are trying to design here is the way of exchanging LAs between OLA/Dashboard and institution with local SIS via EWP network.

> * [ ]  3. Would this problem be solved just by putting the ErasmusDashboard in the red arrow? Then the information would go from OLA > ED > Vienna

The problem with this arrow is that the student is using OLA and the **local** coordinator (from the same institution) is using local SIS. I'm afraid this would not help.

We were talking about these scenarios recently and probably will publish some ideas soon.

**Comment by pleys** [comment]
Diagrams were not accurate indeed. 

Correct diagrams:

**1 LA - OLA**
![1_flow_LA_OLA](https://user-images.githubusercontent.com/19302341/59617655-02e7ab80-9127-11e9-8464-23b42fe82ffe.JPG)

**2 LA - SIS**
![2_flow_LA_SIS](https://user-images.githubusercontent.com/19302341/59617720-227ed400-9127-11e9-90f7-a4226603d4c5.jpg)

**3 LA - OLA - SIS**
![3_flow_LA_OLA_SIS](https://user-images.githubusercontent.com/19302341/59658763-e5592700-91a4-11e9-9b7f-351c9e9ab0d6.JPG)

**Comment by pleys** [comment]
Diagrams were not accurate indeed. 

Correct diagrams:

### 1 LA - OLA
![1_flow_LA_OLA](https://user-images.githubusercontent.com/19302341/59617655-02e7ab80-9127-11e9-8464-23b42fe82ffe.JPG)

**2 LA - SIS**
![2_flow_LA_SIS](https://user-images.githubusercontent.com/19302341/59617720-227ed400-9127-11e9-90f7-a4226603d4c5.jpg)

**3 LA - OLA - SIS**
![3_flow_LA_OLA_SIS](https://user-images.githubusercontent.com/19302341/59617737-2e6a9600-9127-11e9-9723-9d0c88e30938.JPG)

**Comment by BavoNootaert** [comment]
I still have some questions about the diagrams.

1. In all three there is an arrow from EWP to 'LA status is updated in E+ App'. Which API is that? Which hosts exactly are communicating here?
2. On the right hand sides of the first and third diagrams there are three arrows (one to E+, see above, one to OLA, and one to the local SIS; in the second diagram, the two arrows to Ghent can be merged). How should that be interpreted? E.g. in the third diagram, Ghent sends its approval to Vienna. If Vienna uses OLA, wouldn't it be Vienna's responsibility to send the data to OLA, not Ghent's?

**Comment by pleys** [comment]
> In all three there is an arrow from EWP to 'LA status is updated in E+ App'. Which API is that? Which hosts exactly are communicating here?

This would be a new API that was discussed in the Brussels meeting. I don't think that API has been specified.

> in the second diagram, the two arrows to Ghent can be merged. 

I use two arrows to make clear that both the student and coordinator can consult the LA via the tools Ghent provides for them. Bottom part of diagrams is student view, part below is coordinators view.

> How should that be interpreted? E.g. in the third diagram, Ghent sends its approval to Vienna. If Vienna uses OLA, wouldn't it be Vienna's responsibility to send the data to OLA, not Ghent's?

This is the main question: how can EWP support a scenario where Vienna uses OLA/Dashboard for students and local SIS for coordinators. We could argue that the link between OLA/Dashboard and local SIS is Vienna's problem and that EWP only deals with local SIS Vienna. However, than we don't cater for an important use case that was suggested by the OLA-team. That is the main question of this topic, how could EWP cater for a scenario where Vienna uses OLA/Dashboard for students and local SIS for coordinators?
