### ISSUE TITLE
How to change the name of University and PIC number

### ISSUE THREAD

**Issue by Dubravko1** [erasmus-without-paper/issues#34]
Dear Dashboard team.
Would you be so kind to change our University name and PIC number.
From January 2021 VERN' has achieved Research University status.
We has been elevated to University status having met the requirements of the Nagtional Ministry of Education.
As instructed from EU Commission we received new PIC number.
how can we  change Name of University and PIC number.
Thank you.
Kind regards,
Dubravko

**Comment by janinamincer-daszkiewicz** [comment]
*Where* do you want to change these data?

**Comment by Dubravko1** [comment]
In there Erasmus dashboard platfomr at https://www.erasmus-dashboard.eu/account/login

Thank you Kind regards,

[Veleučilište Vern']
Dubravko Kraus, mag.rel.int. et dip., MBA
Ured za međunarodnu suradnju / Office for International Cooperation
Sveučilište VERN' / VERN' University
Palmotićeva ulica 82/1, HR - 10000 ZAGREB
T. +385.1.4881.837, F. +385.1.4881.830
E. ***@***.******@***.***>, W. www.vern.hr<http://www.vern.hr/>

**Comment by janinamincer-daszkiewicz** [comment]
Please, write directly to the Dashboard developers.
