### ISSUE TITLE
Contact List of All Providers

### ISSUE THREAD

**Issue by sascoms** [erasmus-without-paper/issues#35]
Hi,

Is it possible to have or prepare a contact list of all providers including E+ dashboard and in-house SIS developers?

This is important as sometimes we need to contact eachother for test purposes or reporting issues related to EWP services.

As as suggestion, we can also create an email list if requested including all the developers interested.

**Comment by janinamincer-daszkiewicz** [comment]
Isn't the same available here: https://registry.erasmuswithoutpaper.eu/manifestsOverview

**Comment by sascoms** [comment]
No. I meant the emails of the responsible tech people of the EWP providers.

**Comment by janinamincer-daszkiewicz** [comment]
I don't think we are in authority to create and distribute such a list.

**Comment by sascoms** [comment]
Our suggestion is to make the admin-emails information in the manifest files mandatory.

**Comment by georgschermann** [comment]
making it mandatory wouldn't change much, since it would be hard to validate the email address, there is no guarantee that it would stay valid or that it would be regularly read, we stopped serving admin emails because the address was massively spammed

**Comment by janinamincer-daszkiewicz** [comment]
During the Infrastructure forum we suggested to follow some good practices in the EWP network, like using institutional emails and adding information about the providers. Let's hope this will help to have access to contact info.

**Comment by sascoms** [comment]
What is meant by "infrastructure forum"?

**Comment by janinamincer-daszkiewicz** [comment]
> What is meant by "infrastructure forum"?

The meetings we have with mobility software providers on first Wednesdays of each month (2022-02-10, 2022-03-02, 2022-04-06 etc.)
You were present, as I remember.

**Comment by sascoms** [comment]
We were invited and we participated only to the one on 2022-02-10.

And no other invitation email or message we received about the rest.

And still no information received for the one in April.

And also no message received about the infrastructure forum except for the message you requested our email addresses.

**Comment by janinamincer-daszkiewicz** [comment]
- Misunderstanding has been explained in the email correspondence.
- Invitation to the meeting on 2022-04-06 will come in due time, when we are ready with the installation of mailman in domain erasmuswithoupaper.eu and will be able to create a proper mailing list in this domain. This should happen at least a couple of days before the planned meeting.

**Comment by sascoms** [comment]
Thanks @janinamincer-daszkiewicz

**Comment by sascoms** [comment]
May not be the correct place but since the next provider meeting is mentioned here:

The next provider meeting which is on April 6 overlaps with the Erasmus Goes Digital webinar which is on the same day, too.

It would be better to do the provider meeting on a different day or at least not on the same hours that would cause overlapping.

> * Misunderstanding has been explained in the email correspondence.
> * Invitation to the meeting on 2022-04-06 will come in due time, when we are ready with the installation of mailman in domain erasmuswithoupaper.eu and will be able to create a proper mailing list in this domain. This should happen at least a couple of days before the planned meeting.

**Comment by janinamincer-daszkiewicz** [comment]
The hours are:
- Infrastructure Forum:   10-11
- Dashboard webinar:     11-12
- EWP Network webinar: 14-15

I understand your point but it is really difficult to find available slots.

**Comment by sascoms** [comment]
That seems fine. Thanks for the hours information.
