### ISSUE TITLE
Proposal/Changes Decision Procedures

### ISSUE THREAD

**Issue by sascoms** [erasmus-without-paper/issues#36]
Hello,

We have some questions arising from the issues in other repos:
- how the decisions for changes in repos are made? 
- is there any procedure or document for proposed improvements/changes or any other proposals to be accepted?

There are some more questions related but those depends on the answers.

As a quick example, some proposals and issues for CNR parameters have been pending for a long time. 
Created time of those issues:
- 2017 
- 2020 September
- 2021 May

Thanks in advance,

**Comment by georgschermann** [comment]
There is currently no defined/documented procedure for changes, etc. I am aware of. The last coordinated/funded EWP project ended in 2019. A few EWP partners are currently working in the EDSSI project and do some coordination there: EUF, Universities of Ghent, Warsaw, Thessaloniki(OLA) and Porto(Dashboard).

Change proposals / Merge requests would have good chances of being added to EWP if they get approval by these (and as many other partners as possible).

**Comment by umesh-qs** [comment]
I am surprised  no one from the EWP Consortia (not sure who all are part of it. If someone can provide a list it will be helpful) has responded to it so far including @jpbacelar.

**Comment by janinamincer-daszkiewicz** [comment]
Now, in May 2023 the governance in the EWP network is well defined.
There are Infrastructure Forum meetings, there are voting, there is DG EAC in charge.
