### ISSUE TITLE
Statistics showing network activity

### ISSUE THREAD

**Issue by janinamincer-daszkiewicz** [erasmus-without-paper/issues#40]
During the Infrastructure Forum meeting today we discussed the possibility to gather various statistics showing network activity. Some ideas:
- Number of requests per API and endpoint - successful, ending with error.
- Number of CNRs obtained.

Does it make sense? What else could we monitor?
Could you share this statistics with EWP tech team? As yet unofficially, we will not yet share it with anybody outside the team.

**Comment by janinamincer-daszkiewicz** [comment]
Please, share your opinion.

**Comment by georgschermann** [comment]
we have no need/desire for network wide statistics, but could rather easily provide such if needed

**Comment by LDeprez** [comment]
We could also provide such info

**Comment by janinamincer-daszkiewicz** [comment]
We abandoned this idea.
