### ISSUE TITLE
Central server for storing error reports

### ISSUE THREAD

**Issue by janinamincer-daszkiewicz** [erasmus-without-paper/issues#41]
During the Infrastructure Forum meeting today we discussed the possibility to set a new service in the EWP Network, similar to
https://cloud.google.com/error-reporting.

This service would expose API for error reporting, and aggregate errors centrally, for further processing.

What do you think about this idea? Would it help in debugging the network?

**Comment by janinamincer-daszkiewicz** [comment]
Please, share your opinion.

**Comment by LDeprez** [comment]
At Ghent University, we don't see the morevalue of such central error reporting.

**Comment by janinamincer-daszkiewicz** [comment]
Could you add some arguments, please.

**Comment by LDeprez** [comment]
Arguments:
We could make our own statistics for errors on our endpoints + errors we receive when calling other endpoints.
I don't see use cases where error reporting from other applications offers an added value?

**Comment by janinamincer-daszkiewicz** [comment]
The added value is that the authorities see where the errors are and can help, react, etc.

**Comment by janinamincer-daszkiewicz** [comment]
The Monitoring system is in operation: https://stats.erasmuswithoutpaper.eu/monitoring.
