### ISSUE TITLE
Is it possible to use a standardized set of term identifiers?

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/issues#7]
Would it be safe to assume that all the partners and all the HEIs use **semesters only** (and don't use _trimesters_ nor _quarters_) to partition their academic years? (My guess is _no_.)

**Comment by georgschermann** [comment]
some of our customers use trimesters, whole years, short terms like summer classes, etc. but don't know how relevant all of them are for erasmus
also start/end dates differ between nearly all HEIs

**Comment by wrygiel** [comment]
> some of our customers use trimesters, whole years, short terms like summer classes

Oh, even summer classes. Didn't even think of that. Do all these terms have separate IDs in your system?

This question is interesting in context of the model for the IMA (Interinstitutional Mobility Agreement = Bilateral Agreement). As far as I know, these agreements refer to academic terms in some ways. Could these agreements work if - for example - these academic terms were replaced with start/end dates?

**Comment by vickalaser** [comment]
Almost all UK HEIs are trimester with the last term dedicated mainly but not wholly to examinations.

**Comment by georgschermann** [comment]
all these terms have seperate ids
start and end dates may be subject to change and therefor not the best identifier

**Comment by wrygiel** [comment]
> Would it be safe to assume that all the partners and all the HEIs use **semesters only** (and don't use _trimesters_ nor _quarters_) to partition their academic years? (My guess is _no_.)

I think it's now quite clear that the answer to this question is **no**. :)
