### ISSUE TITLE
IMA or IIA?

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/issues#8]
Which of these abbreviations is the proper one for _Interinstitutional Mobility Agreement_ entity? IMA or IIA?

I currently use IMA ([since March](https://github.com/erasmus-without-paper/general-issues/issues/6)), but if you have already agreed to use IIA, then I will update my documents.

**Comment by wrygiel** [comment]
@erasmus-without-paper/wp2 - BTW, could you comment on this?

**Comment by StefanJahnke** [comment]
Hello,
I suggest using Interinstitutional Agreement (IIA), as it is the official name by the European Commission and used throughout all documents.

**Comment by wrygiel** [comment]
> official name by the European Commission 

Good to know! Thanks. I will update all documents soon.

**Comment by wrygiel** [comment]
All occurrences replaced and all repositories renamed.
